---
title: "COVID-19 in the US"
author: "Shaun Ratcliff"
date: "04/02/2021"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

load('Data/covid.RData')

library(tidyverse)
library(scales)
library(gganimate)


```



## Using gganimate to create animated graphs 


```{r covid_states, fig.width = 3.5, fig.height = 2.5}


covid.smooth.data_county %>% 
  filter(state %in% c('New York', 'Florida', 'Texas')) %>%
  group_by(state, date) %>% 
  dplyr::summarise(cases_14days = sum(cases_14days)) %>%

ggplot(aes(x = date, y = cases_14days, colour = state)) +
  
  geom_vline(xintercept = as.Date("2020-06-20"), 
             size = .5, linetype = 'dashed', alpha = 1) +
  
  annotate("text", x = as.Date("2020-08-01"), y = 15000, size = 2,
             label = "Summer") +
  
  geom_vline(xintercept = as.Date("2020-09-22"), 
             size = .5, linetype = 'dashed', alpha = 1) +

  
  geom_line(size = 1) + 
  geom_segment(aes(xend = as.Date("2020-12-01"), yend = cases_14days), 
               linetype = 2) + 
  geom_point(size = 2) + 
  geom_text(aes(x = as.Date("2020-12-01"), 
                label = state), hjust = 0, size = 2) + 
  scale_x_date(limits=as.Date(c("2020-01-22", "2020-12-30"))) +
  scale_y_continuous(labels = comma) +
  labs(title = 'Confirmed cases of COVID-19, by state',
       y = 'New confirmed cases (Rolling 14-day average)',
       x = 'Date') + 
  theme_minimal() +
  theme(plot.title = element_text(size = 7, face = "bold", hjust = 0),
          strip.background = element_blank(),
          panel.border = element_blank(),
          panel.grid = element_blank(),
          axis.title = element_text(size = 5),
          legend.title = element_blank(),
          legend.text = element_text(size = 5),
          legend.position = "none",
          axis.text = element_text(size = 4)) +
    transition_reveal(date) 


```


